# Generated by Django 2.1.4 on 2018-12-18 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nextgenmusic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listen_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('id_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextgenmusic.Song')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
