# Generated by Django 2.1.4 on 2018-12-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextgenmusic', '0002_listen_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listen_count',
            name='count',
            field=models.IntegerField(blank=True),
        ),
    ]
