# Generated by Django 2.1.4 on 2018-12-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextgenmusic', '0003_auto_20181218_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listen_count',
            name='count',
            field=models.IntegerField(),
        ),
    ]
