# Generated by Django 2.1.4 on 2018-12-18 19:44

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nextgenmusic', '0004_auto_20181218_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
