# Generated by Django 2.1.4 on 2018-12-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextgenmusic', '0006_auto_20181218_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song_author',
            name='id_author',
        ),
        migrations.RemoveField(
            model_name='song_author',
            name='id_song',
        ),
        migrations.RemoveField(
            model_name='song_playlist',
            name='id_playlist',
        ),
        migrations.RemoveField(
            model_name='song_playlist',
            name='id_song',
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(to='nextgenmusic.Song'),
        ),
        migrations.AddField(
            model_name='song',
            name='authors',
            field=models.ManyToManyField(to='nextgenmusic.Author'),
        ),
        migrations.DeleteModel(
            name='Song_Author',
        ),
        migrations.DeleteModel(
            name='Song_Playlist',
        ),
    ]
