# Generated by Django 2.1.4 on 2018-12-19 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nextgenmusic', '0007_auto_20181218_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listen_count',
            name='id_song',
        ),
        migrations.RemoveField(
            model_name='listen_count',
            name='id_user',
        ),
        migrations.DeleteModel(
            name='Listen_count',
        ),
    ]
