# Generated by Django 2.1.4 on 2019-01-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextgenmusic', '0011_auto_20190101_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listen_count',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
