# Generated by Django 2.1.4 on 2019-01-09 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nextgenmusic', '0012_auto_20190109_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listen_count',
            old_name='id_song',
            new_name='song',
        ),
        migrations.RenameField(
            model_name='listen_count',
            old_name='id_user',
            new_name='user',
        ),
    ]
