# Generated by Django 2.1.4 on 2019-01-09 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nextgenmusic', '0013_auto_20190110_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listen_count',
            old_name='song',
            new_name='id_song',
        ),
        migrations.RenameField(
            model_name='listen_count',
            old_name='user',
            new_name='id_user',
        ),
    ]
